# Generated by Django 5.2.6 on 2025-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "management_no",
                    models.CharField(max_length=20, unique=True, verbose_name="管理No"),
                ),
                ("site_name", models.CharField(max_length=200, verbose_name="現場名")),
                ("site_address", models.TextField(verbose_name="現場住所")),
                ("work_type", models.CharField(max_length=50, verbose_name="種別")),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("受注", "受注"),
                            ("NG", "NG"),
                            ("A", "A"),
                            ("検討中", "検討中"),
                        ],
                        default="検討中",
                        max_length=10,
                        verbose_name="受注ヨミ",
                    ),
                ),
                (
                    "estimate_issued_date",
                    models.DateField(blank=True, null=True, verbose_name="見積書発行日"),
                ),
                (
                    "estimate_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="見積金額(税込)",
                    ),
                ),
                (
                    "parking_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=8,
                        verbose_name="駐車場代(税込)",
                    ),
                ),
                (
                    "contractor_name",
                    models.CharField(max_length=100, verbose_name="請負業者名"),
                ),
                ("contractor_address", models.TextField(verbose_name="請負業者住所")),
                (
                    "project_manager",
                    models.CharField(max_length=50, verbose_name="案件担当"),
                ),
                (
                    "payment_due_date",
                    models.DateField(blank=True, null=True, verbose_name="入金予定日"),
                ),
                (
                    "work_start_date",
                    models.DateField(blank=True, null=True, verbose_name="工事開始日"),
                ),
                (
                    "work_end_date",
                    models.DateField(blank=True, null=True, verbose_name="工事終了日"),
                ),
                (
                    "contract_date",
                    models.DateField(blank=True, null=True, verbose_name="契約日"),
                ),
                (
                    "invoice_issued",
                    models.BooleanField(default=False, verbose_name="請求書発行"),
                ),
                (
                    "expense_item_1",
                    models.CharField(blank=True, max_length=100, verbose_name="諸経費項目①"),
                ),
                (
                    "expense_amount_1",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=8,
                        verbose_name="諸経費代(税込)①",
                    ),
                ),
                (
                    "expense_item_2",
                    models.CharField(blank=True, max_length=100, verbose_name="諸経費項目②"),
                ),
                (
                    "expense_amount_2",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=8,
                        verbose_name="諸経費代(税込)②",
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="請求額実請求",
                    ),
                ),
                (
                    "amount_difference",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="増減"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
