# Generated by Django 5.2.6 on 2025-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="work_end_completed",
            field=models.BooleanField(default=False, verbose_name="工事終了完了"),
        ),
        migrations.AddField(
            model_name="project",
            name="work_start_completed",
            field=models.BooleanField(default=False, verbose_name="工事開始完了"),
        ),
    ]
