# Generated by Django 5.2.6 on 2025-09-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0002_project_work_end_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="estimate_not_required",
            field=models.BooleanField(default=False, verbose_name="見積書不要"),
        ),
    ]
