# Generated by Django 5.2.6 on 2025-09-21 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0003_project_estimate_not_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressStepTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ステップ名")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-circle", max_length=50, verbose_name="アイコン"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="デフォルト表示"),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="システム項目"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("date", "日付"),
                            ("checkbox", "チェックボックス"),
                            ("select", "選択肢"),
                            ("text", "テキスト"),
                        ],
                        default="date",
                        max_length=20,
                        verbose_name="フィールドタイプ",
                    ),
                ),
                (
                    "field_options",
                    models.JSONField(blank=True, null=True, verbose_name="フィールドオプション"),
                ),
            ],
            options={
                "verbose_name": "進捗ステップテンプレート",
                "verbose_name_plural": "進捗ステップテンプレート一覧",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectProgressStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="アクティブ")),
                ("is_completed", models.BooleanField(default=False, verbose_name="完了")),
                ("value", models.JSONField(blank=True, null=True, verbose_name="値")),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="完了日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_steps",
                        to="order_management.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.progresssteptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト進捗ステップ",
                "verbose_name_plural": "プロジェクト進捗ステップ一覧",
                "ordering": ["order", "template__order"],
                "unique_together": {("project", "template")},
            },
        ),
    ]
