# Generated by Django 4.2.6 on 2025-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0004_progresssteptemplate_projectprogressstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_items",
            field=models.JSONField(blank=True, default=dict, verbose_name="追加項目"),
        ),
    ]
