# Generated by Django 5.2.6 on 2025-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0005_project_additional_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="業者名")),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="担当者名"),
                ),
                ("specialties", models.TextField(blank=True, verbose_name="専門分野")),
                (
                    "is_ordering",
                    models.BooleanField(default=False, verbose_name="発注業者"),
                ),
                (
                    "is_receiving",
                    models.BooleanField(default=False, verbose_name="受注業者"),
                ),
                ("is_supplier", models.BooleanField(default=False, verbose_name="資材屋")),
                ("is_other", models.BooleanField(default=False, verbose_name="その他")),
                (
                    "other_description",
                    models.CharField(blank=True, max_length=100, verbose_name="その他内容"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="アクティブ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "業者",
                "verbose_name_plural": "業者一覧",
                "ordering": ["-is_receiving", "-is_active", "name"],
            },
        ),
    ]
