# Generated by Django 5.2.6 on 2025-09-21 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0006_contractor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractor",
            options={
                "ordering": ["-is_ordering", "-is_active", "name"],
                "verbose_name": "業者",
                "verbose_name_plural": "業者一覧",
            },
        ),
    ]
