# Generated by Django 5.2.6 on 2025-09-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0007_alter_contractor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="survey_required",
            field=models.BooleanField(default=False, verbose_name="現地調査必要"),
        ),
        migrations.AddField(
            model_name="project",
            name="survey_status",
            field=models.CharField(
                choices=[
                    ("not_required", "不要"),
                    ("required", "必要"),
                    ("scheduled", "予定済み"),
                    ("in_progress", "調査中"),
                    ("completed", "完了"),
                ],
                default="not_required",
                max_length=20,
                verbose_name="現地調査ステータス",
            ),
        ),
    ]
