# Generated by Django 5.2.6 on 2025-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0008_project_survey_required_project_survey_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="account_holder",
            field=models.CharField(blank=True, max_length=100, verbose_name="口座名義"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="口座番号"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("ordinary", "普通"), ("current", "当座")],
                default="ordinary",
                max_length=10,
                verbose_name="口座種別",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="銀行名"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="branch_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="支店名"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                help_text="月末締めの場合は31、20日締めの場合は20",
                null=True,
                verbose_name="締め日",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="payment_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("project_end", "案件完了時"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の支払日（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="実際の支払金額（請求額と異なる場合に使用）",
                max_digits=10,
                null=True,
                verbose_name="支払金額",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_executed_date",
            field=models.DateField(
                blank=True, help_text="実際に支払を行った日", null=True, verbose_name="支払実行日"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_memo",
            field=models.TextField(
                blank=True, help_text="支払に関する特記事項", verbose_name="支払メモ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_scheduled_date",
            field=models.DateField(
                blank=True, help_text="業者への支払予定日", null=True, verbose_name="支払予定日"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("scheduled", "予定"),
                    ("executed", "支払済み"),
                    ("overdue", "遅延"),
                    ("cancelled", "キャンセル"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="支払状況",
            ),
        ),
    ]
