# Generated by Django 5.2.6 on 2025-09-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0009_contractor_account_holder_contractor_account_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="費目名")),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("business_outsourcing", "業務委託費"),
                            ("insurance", "保険"),
                            ("legal_fee", "弁護士費用"),
                            ("accounting_fee", "税理士費用"),
                            ("executive_compensation", "役員報酬"),
                            ("rent", "家賃"),
                            ("utilities", "光熱費"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="費目種別",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="月額"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="終了日"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="アクティブ")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "固定費",
                "verbose_name_plural": "固定費一覧",
                "ordering": ["cost_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="VariableCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="費目名")),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("sales_expense", "営業費"),
                            ("marketing_expense", "マーケティング費"),
                            ("admin_expense", "管理費"),
                            ("travel_expense", "交通費"),
                            ("entertainment_expense", "接待費"),
                            ("other", "その他"),
                        ],
                        max_length=30,
                        verbose_name="費目種別",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="金額"
                    ),
                ),
                ("incurred_date", models.DateField(verbose_name="発生日")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_management.project",
                        verbose_name="関連案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "変動費",
                "verbose_name_plural": "変動費一覧",
                "ordering": ["-incurred_date"],
            },
        ),
    ]
