# Generated by Django 5.2.6 on 2025-09-23 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0010_fixedcost_variablecost"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="発注番号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("ordered", "発注済み"),
                            ("delivered", "納品済み"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="発注日")),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="納期"),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="実際の納品日"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="総額"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.contractor",
                        verbose_name="資材業者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_orders",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "資材発注",
                "verbose_name_plural": "資材発注一覧",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=200, verbose_name="資材名")),
                ("specification", models.TextField(blank=True, verbose_name="仕様・規格")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="数量"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="単位")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="単価"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="小計"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_management.materialorder",
                        verbose_name="発注",
                    ),
                ),
            ],
            options={
                "verbose_name": "資材発注項目",
                "verbose_name_plural": "資材発注項目一覧",
            },
        ),
    ]
