# Generated by Django 5.2.6 on 2025-09-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0011_materialorder_materialorderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, unique=True, verbose_name="請求書番号"),
                ),
                ("client_name", models.CharField(max_length=200, verbose_name="受注先名")),
                ("client_address", models.TextField(blank=True, verbose_name="受注先住所")),
                ("issue_date", models.DateField(verbose_name="発行日")),
                ("due_date", models.DateField(verbose_name="支払期限")),
                ("billing_period_start", models.DateField(verbose_name="請求期間開始")),
                ("billing_period_end", models.DateField(verbose_name="請求期間終了")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="小計（税抜）"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=5,
                        verbose_name="消費税率",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="消費税額"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="合計金額"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("issued", "発行済み"),
                            ("sent", "送付済み"),
                            ("paid", "入金済み"),
                            ("overdue", "延滞"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=100, verbose_name="作成者"),
                ),
            ],
            options={
                "verbose_name": "請求書",
                "verbose_name_plural": "請求書一覧",
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500, verbose_name="項目名")),
                (
                    "work_period_start",
                    models.DateField(blank=True, null=True, verbose_name="作業期間開始"),
                ),
                (
                    "work_period_end",
                    models.DateField(blank=True, null=True, verbose_name="作業期間終了"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=1, max_digits=10, verbose_name="数量"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="式", max_length=20, verbose_name="単位"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="単価"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_management.invoice",
                        verbose_name="請求書",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求書明細",
                "verbose_name_plural": "請求書明細一覧",
                "ordering": ["order", "id"],
            },
        ),
    ]
