# Generated by Django 4.2.6 on 2025-10-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0008_contractor_account_holder_contractor_account_number_and_more",
        ),
        ("order_management", "0014_migrate_status_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completion_date",
            field=models.DateField(
                blank=True,
                help_text="工事が完工した日（発生主義売上の基準日）",
                null=True,
                verbose_name="完工日",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="invoice_issue_datetime",
            field=models.DateTimeField(
                blank=True, help_text="請求書を発行した日時", null=True, verbose_name="請求書発行日時"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_received_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="実際の入金金額（請求額と異なる場合に使用）",
                max_digits=10,
                null=True,
                verbose_name="入金金額",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_received_date",
            field=models.DateField(
                blank=True, help_text="元請から実際に入金があった日", null=True, verbose_name="入金実行日"
            ),
        ),
        migrations.CreateModel(
            name="CashFlowTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("revenue_accrual", "売上（発生）"),
                            ("revenue_cash", "売上（入金）"),
                            ("expense_accrual", "支出（発生）"),
                            ("expense_cash", "支出（出金）"),
                        ],
                        max_length=20,
                        verbose_name="取引種別",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="取引日")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="金額"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="説明"),
                ),
                (
                    "is_planned",
                    models.BooleanField(default=False, verbose_name="予定/実績"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_transactions",
                        to="order_management.project",
                        verbose_name="関連案件",
                    ),
                ),
                (
                    "related_subcontract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subcontract_management.subcontract",
                        verbose_name="関連外注",
                    ),
                ),
            ],
            options={
                "verbose_name": "キャッシュフロー取引",
                "verbose_name_plural": "キャッシュフロー取引一覧",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_date", "transaction_type"],
                        name="order_manag_transac_b3fc39_idx",
                    ),
                    models.Index(
                        fields=["project", "transaction_type"],
                        name="order_manag_project_4334fd_idx",
                    ),
                ],
            },
        ),
    ]
