# Generated by Django 4.2.6 on 2025-10-26 21:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order_management", "0015_add_cashflow_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="シナリオ名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("worst", "最悪シナリオ"),
                            ("normal", "通常シナリオ"),
                            ("best", "最良シナリオ"),
                            ("custom", "カスタム"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="シナリオタイプ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "conversion_rate_neta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("30.00"),
                        help_text="ネタ→完工への成約確率",
                        max_digits=5,
                        verbose_name="ネタ成約率（%）",
                    ),
                ),
                (
                    "conversion_rate_waiting",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="施工日待ち→完工への成約確率",
                        max_digits=5,
                        verbose_name="施工日待ち成約率（%）",
                    ),
                ),
                (
                    "cost_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        help_text="売上に対する原価の割合",
                        max_digits=5,
                        verbose_name="原価率（%）",
                    ),
                ),
                (
                    "fixed_cost_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="現在の固定費に対する係数（1.0=現状維持）",
                        max_digits=4,
                        verbose_name="固定費係数",
                    ),
                ),
                (
                    "variable_cost_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="過去平均変動費に対する係数",
                        max_digits=4,
                        verbose_name="変動費係数",
                    ),
                ),
                (
                    "forecast_months",
                    models.IntegerField(
                        default=12, help_text="1-24ヶ月", verbose_name="予測月数"
                    ),
                ),
                (
                    "seasonality_enabled",
                    models.BooleanField(
                        default=True, help_text="過去の季節性パターンを考慮", verbose_name="季節性考慮"
                    ),
                ),
                (
                    "forecast_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="計算された予測データ",
                        verbose_name="予測結果",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="アクティブ")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="デフォルトシナリオ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "売上予測シナリオ",
                "verbose_name_plural": "売上予測シナリオ一覧",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scenario_type", "is_active"],
                        name="order_manag_scenari_3a9b9e_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="order_manag_created_122eba_idx",
                    ),
                ],
            },
        ),
    ]
