# Generated by Django 4.2.6 on 2025-10-26 21:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order_management", "0016_add_forecast_scenario"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonalityIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "january_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="1月指数",
                    ),
                ),
                (
                    "february_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="2月指数",
                    ),
                ),
                (
                    "march_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="3月指数",
                    ),
                ),
                (
                    "april_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="4月指数",
                    ),
                ),
                (
                    "may_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="5月指数",
                    ),
                ),
                (
                    "june_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="6月指数",
                    ),
                ),
                (
                    "july_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="7月指数",
                    ),
                ),
                (
                    "august_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="8月指数",
                    ),
                ),
                (
                    "september_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="9月指数",
                    ),
                ),
                (
                    "october_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="10月指数",
                    ),
                ),
                (
                    "november_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="11月指数",
                    ),
                ),
                (
                    "december_index",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("3.00")),
                        ],
                        verbose_name="12月指数",
                    ),
                ),
                (
                    "use_auto_calculation",
                    models.BooleanField(
                        default=True,
                        help_text="ONの場合は過去データから自動計算、OFFの場合は手動設定値を使用",
                        verbose_name="自動計算を使用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "forecast_scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonality_index",
                        to="order_management.forecastscenario",
                        verbose_name="予測シナリオ",
                    ),
                ),
            ],
            options={
                "verbose_name": "季節性指数",
                "verbose_name_plural": "季節性指数",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="レポートタイトル")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "月次経営レポート"),
                            ("project", "プロジェクト別レポート"),
                            ("cashflow", "キャッシュフローレポート"),
                            ("forecast", "予測レポート"),
                            ("progress", "進捗レポート"),
                        ],
                        max_length=20,
                        verbose_name="レポートタイプ",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "generated_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成日時"),
                ),
                ("period_start", models.DateField(verbose_name="対象期間開始")),
                ("period_end", models.DateField(verbose_name="対象期間終了")),
                (
                    "report_data",
                    models.JSONField(blank=True, default=dict, verbose_name="レポートデータ"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="PDFファイル",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="公開済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "レポート",
                "verbose_name_plural": "レポート",
                "ordering": ["-generated_date"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "-generated_date"],
                        name="order_manag_report__aa87f0_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="order_manag_period__b083eb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="記録日"
                    ),
                ),
                (
                    "progress_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="0-100%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="進捗率（%）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("on_track", "順調"),
                            ("at_risk", "注意"),
                            ("delayed", "遅延"),
                            ("completed", "完了"),
                        ],
                        default="on_track",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "milestone_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="マイルストーン名"
                    ),
                ),
                (
                    "milestone_date",
                    models.DateField(blank=True, null=True, verbose_name="マイルストーン予定日"),
                ),
                (
                    "milestone_completed",
                    models.BooleanField(default=False, verbose_name="マイルストーン完了"),
                ),
                ("has_risk", models.BooleanField(default=False, verbose_name="リスクあり")),
                (
                    "risk_description",
                    models.TextField(blank=True, verbose_name="リスク内容"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        max_length=20,
                        verbose_name="リスクレベル",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="order_management.project",
                        verbose_name="プロジェクト",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="記録者",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロジェクト進捗",
                "verbose_name_plural": "プロジェクト進捗",
                "ordering": ["-recorded_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-recorded_date"],
                        name="order_manag_project_772883_idx",
                    ),
                    models.Index(
                        fields=["status"], name="order_manag_status_55d400_idx"
                    ),
                    models.Index(
                        fields=["recorded_date"], name="order_manag_recorde_ddb685_idx"
                    ),
                ],
            },
        ),
    ]
