# Generated by Django 4.2.6 on 2025-10-31 05:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "subcontract_management",
            "0009_contractor_average_rating_contractor_certifications_and_more",
        ),
        ("order_management", "0019_comment_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="テンプレート名")),
                ("work_type", models.CharField(max_length=50, verbose_name="施工種別")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("items", models.JSONField(default=list, verbose_name="チェック項目")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "チェックリストテンプレート",
                "verbose_name_plural": "チェックリストテンプレート一覧",
                "ordering": ["work_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClientCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, unique=True, verbose_name="会社名"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="担当者名"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "default_key_handover_location",
                    models.TextField(blank=True, verbose_name="鍵受け渡し場所（デフォルト）"),
                ),
                (
                    "key_handover_notes",
                    models.TextField(blank=True, verbose_name="鍵受け渡し特記事項"),
                ),
                (
                    "completion_report_template",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="completion_templates/",
                        verbose_name="完了報告シートテンプレート",
                    ),
                ),
                (
                    "completion_report_notes",
                    models.TextField(blank=True, verbose_name="完了報告特記事項"),
                ),
                (
                    "approval_threshold",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        help_text="この金額以上の案件は承認が必要",
                        max_digits=10,
                        verbose_name="承認必要金額閾値",
                    ),
                ),
                (
                    "special_notes",
                    models.TextField(blank=True, verbose_name="特記事項・運用ルール"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "元請会社",
                "verbose_name_plural": "元請会社一覧",
                "ordering": ["company_name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("not_required", "承認不要"),
                    ("pending", "承認待ち"),
                    ("approved", "承認済み"),
                    ("rejected", "却下"),
                ],
                default="not_required",
                max_length=20,
                verbose_name="承認ステータス",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
        ),
        migrations.AddField(
            model_name="project",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="承認者",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="key_handover_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="鍵受け渡し日時"),
        ),
        migrations.AddField(
            model_name="project",
            name="key_handover_location",
            field=models.TextField(
                blank=True, help_text="案件ごとの鍵受け渡し場所", verbose_name="鍵受け渡し場所"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="key_handover_notes",
            field=models.TextField(blank=True, verbose_name="鍵受け渡しメモ"),
        ),
        migrations.AddField(
            model_name="project",
            name="priority_score",
            field=models.IntegerField(
                default=0, help_text="自動計算される優先度（高いほど優先）", verbose_name="優先度スコア"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="requires_approval",
            field=models.BooleanField(
                default=False, help_text="金額や条件により承認が必要な案件", verbose_name="承認必要"
            ),
        ),
        migrations.CreateModel(
            name="ProjectChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.JSONField(default=list, verbose_name="チェック項目")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完了日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_management.checklisttemplate",
                        verbose_name="テンプレート",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件チェックリスト",
                "verbose_name_plural": "案件チェックリスト一覧",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("estimate", "見積承認"),
                            ("contractor_assign", "職人アサイン承認"),
                            ("payment", "支払承認"),
                            ("project_start", "案件開始承認"),
                        ],
                        max_length=20,
                        verbose_name="承認種別",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "承認待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                ("request_reason", models.TextField(blank=True, verbose_name="申請理由")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="金額",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "approval_comment",
                    models.TextField(blank=True, verbose_name="承認コメント"),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="却下理由")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="承認日時"),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_logs",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
            ],
            options={
                "verbose_name": "承認履歴",
                "verbose_name_plural": "承認履歴一覧",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="client_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="order_management.clientcompany",
                verbose_name="元請会社",
            ),
        ),
        migrations.CreateModel(
            name="ContractorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="総合評価",
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="品質スコア",
                    ),
                ),
                (
                    "speed_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="スピードスコア",
                    ),
                ),
                (
                    "communication_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="コミュニケーションスコア",
                    ),
                ),
                ("review_comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "would_recommend",
                    models.BooleanField(default=True, verbose_name="次回も依頼したい"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="評価日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="subcontract_management.contractor",
                        verbose_name="職人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_reviews",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
            ],
            options={
                "verbose_name": "職人評価",
                "verbose_name_plural": "職人評価一覧",
                "ordering": ["-reviewed_at"],
                "unique_together": {("contractor", "project")},
            },
        ),
    ]
