# Generated by Django 4.2.6 on 2025-10-31 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order_management", "0020_checklisttemplate_clientcompany_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="asap_requested",
            field=models.BooleanField(
                default=False, help_text="できるだけ早く施工を希望", verbose_name="最短希望"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="invoice_status",
            field=models.CharField(
                choices=[("not_issued", "未発行"), ("issued", "発行済み")],
                default="not_issued",
                max_length=20,
                verbose_name="請求書発行ステータス",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="work_date_specified",
            field=models.BooleanField(
                default=False, help_text="施工日を具体的に指定する", verbose_name="施工日指定あり"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_due_date",
            field=models.DateField(null=True, verbose_name="入金予定日"),
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_files/%Y/%m/", verbose_name="ファイル"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="ファイル名")),
                ("file_size", models.IntegerField(verbose_name="ファイルサイズ（バイト）")),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ファイルタイプ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="アップロード日時"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="アップロード者",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件ファイル",
                "verbose_name_plural": "案件ファイル一覧",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
