# Generated by Django 4.2.6 on 2025-10-31 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0021_project_asap_requested_project_invoice_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="comment_attachments/%Y/%m/%d/", verbose_name="ファイル"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="ファイル名")),
                ("file_size", models.IntegerField(verbose_name="ファイルサイズ（バイト）")),
                ("file_type", models.CharField(max_length=100, verbose_name="ファイルタイプ")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="アップロード日時"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="order_management.comment",
                        verbose_name="コメント",
                    ),
                ),
            ],
            options={
                "verbose_name": "コメント添付ファイル",
                "verbose_name_plural": "コメント添付ファイル一覧",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
