# Generated by Django 4.2.6 on 2025-10-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0022_commentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="construction_assignees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="施工の担当者リスト（職人）",
                verbose_name="施工担当者",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="construction_status",
            field=models.CharField(
                choices=[
                    ("waiting", "着工日待ち"),
                    ("in_progress", "工事中"),
                    ("completed", "完工"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="工事ステータス",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimate_status",
            field=models.CharField(
                choices=[
                    ("not_issued", "未発行"),
                    ("issued", "見積もり書発行"),
                    ("under_review", "見積もり審査中"),
                    ("approved", "承認"),
                ],
                default="not_issued",
                max_length=20,
                verbose_name="見積もりステータス",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="survey_assignees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="現地調査の担当者リスト（職人）",
                verbose_name="現調担当者",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="survey_date",
            field=models.DateField(blank=True, null=True, verbose_name="現調日"),
        ),
        migrations.AddField(
            model_name="project",
            name="witness_assignee_type",
            field=models.CharField(
                choices=[("internal", "自社"), ("contractor", "職人")],
                default="internal",
                max_length=20,
                verbose_name="立ち会い担当者タイプ",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="witness_assignees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="立ち会いの担当者リスト（自社または職人）",
                verbose_name="立ち会い担当者",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="witness_date",
            field=models.DateField(blank=True, null=True, verbose_name="立ち会い日"),
        ),
        migrations.AddField(
            model_name="project",
            name="witness_status",
            field=models.CharField(
                choices=[
                    ("waiting", "立ち会い待ち"),
                    ("in_progress", "立ち会い中"),
                    ("completed", "完了"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="立ち会いステータス",
            ),
        ),
    ]
