# Generated by Django 4.2.6 on 2025-11-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0023_project_construction_assignees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("ネタ", "ネタ"),
                    ("施工日待ち", "施工日待ち"),
                    ("進行中", "進行中"),
                    ("完工", "完工"),
                    ("NG", "NG"),
                ],
                default="ネタ",
                max_length=20,
                verbose_name="受注ヨミ",
            ),
        ),
    ]
