# Generated by Django 4.2.6 on 2025-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0024_alter_project_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("ネタ", "ネタ"),
                    ("A", "A"),
                    ("B", "B"),
                    ("受注確定", "受注確定"),
                    ("NG", "NG"),
                ],
                default="ネタ",
                max_length=20,
                verbose_name="受注ヨミ",
            ),
        ),
    ]
