# Generated by Django 4.2.6 on 2025-11-09 09:07

from django.db import migrations, models


def populate_current_stage(apps, schema_editor):
    """既存プロジェクトの進捗状況を計算して保存"""
    Project = apps.get_model('order_management', 'Project')

    for project in Project.objects.all():
        # get_current_project_stage() のロジックを再現
        complex_fields = project.additional_items.get('complex_step_fields', {}) if project.additional_items else {}

        # 完工日チェック
        if project.work_end_completed or complex_fields.get('completion_completed'):
            stage, color = '完工', 'verified'
        elif complex_fields.get('completion_actual_date') or project.work_end_date:
            stage, color = '完工', 'success'
        # 着工日チェック
        elif project.work_start_completed:
            stage, color = '工事中', 'verified'
        elif complex_fields.get('construction_start_actual_date'):
            stage, color = '工事中', 'success'
        elif complex_fields.get('construction_start_scheduled_date') or project.work_start_date:
            stage, color = '着工日待ち', 'warning'
        # 見積もりチェック
        elif project.estimate_issued_date or complex_fields.get('estimate_issued_date'):
            stage, color = '見積もり審査中', 'warning'
        # 現調チェック
        elif complex_fields.get('survey_actual_date'):
            stage, color = '現調済み', 'success'
        elif complex_fields.get('survey_scheduled_date'):
            stage, color = '現調待ち', 'warning'
        # 立ち会いチェック
        elif complex_fields.get('attendance_actual_date'):
            stage, color = '立ち会い済み', 'success'
        elif complex_fields.get('attendance_scheduled_date'):
            stage, color = '立ち会い待ち', 'warning'
        else:
            stage, color = '未開始', 'secondary'

        project.current_stage = stage
        project.current_stage_color = color
        project.save(update_fields=['current_stage', 'current_stage_color'])


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0025_alter_project_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="current_stage",
            field=models.CharField(
                default="未開始",
                help_text="JavaScriptで計算された進捗状況を保存（完工、工事中、着工日待ちなど）",
                max_length=20,
                verbose_name="現在の進捗状況",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="current_stage_color",
            field=models.CharField(
                default="secondary",
                help_text="verified, success, warning, secondary",
                max_length=20,
                verbose_name="進捗状況の色",
            ),
        ),
        migrations.RunPython(populate_current_stage, migrations.RunPython.noop),
    ]
