# Generated by Django 4.2.6 on 2025-11-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0026_project_current_stage_project_current_stage_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completion_report_content",
            field=models.TextField(
                blank=True,
                help_text="完了報告の本文（元請会社のテンプレートから自動入力可能）",
                verbose_name="完了報告内容",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_report_date",
            field=models.DateField(blank=True, null=True, verbose_name="完了報告日"),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_report_notes",
            field=models.TextField(
                blank=True, help_text="完了報告に関する特記事項", verbose_name="完了報告メモ"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_report_status",
            field=models.CharField(
                choices=[
                    ("not_created", "未作成"),
                    ("draft", "下書き"),
                    ("submitted", "提出済み"),
                ],
                default="not_created",
                max_length=20,
                verbose_name="完了報告ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("ネタ", "ネタ"),
                    ("A", "A"),
                    ("B", "B"),
                    ("受注確定", "受注確定"),
                    ("NG", "NG"),
                ],
                default="ネタ",
                max_length=20,
                verbose_name="受注ヨミ",
            ),
        ),
    ]
