# Generated by Django 4.2.6 on 2025-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0027_project_completion_report_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completion_report_completed",
            field=models.BooleanField(
                default=False, help_text="完了報告が完了したかどうか", verbose_name="完了報告完了"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_report_file",
            field=models.FileField(
                blank=True,
                help_text="完了報告のPDF/Excelファイル（アップロード）",
                null=True,
                upload_to="completion_reports/",
                verbose_name="完了報告ファイル",
            ),
        ),
    ]
