# Generated by Django 4.2.6 on 2025-11-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0028_project_completion_report_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="client_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="元請名"),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.CharField(blank=True, max_length=50, verbose_name="案件担当"),
        ),
    ]
