# Generated by Django 4.2.6 on 2025-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0029_alter_project_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="progress_comment",
            field=models.TextField(
                blank=True, help_text="案件の進捗に関する詳細なコメント", verbose_name="進捗コメント"
            ),
        ),
    ]
