# Generated by Django 4.2.6 on 2025-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0030_project_progress_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="detailed_comments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="複数の詳細コメントを時系列で保存",
                verbose_name="詳細コメント履歴",
            ),
        ),
    ]
