# Generated by Django 4.2.6 on 2025-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0031_project_detailed_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                help_text="月末締めの場合は31、20日締めの場合は20",
                null=True,
                verbose_name="締め日",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("custom", "その他"),
                ],
                default="monthly",
                help_text="案件登録時のデフォルト値として使用されます",
                max_length=20,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の支払日（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="website",
            field=models.URLField(
                blank=True, help_text="会社のウェブサイトURL", verbose_name="ホームページ"
            ),
        ),
    ]
