# Generated by Django 4.2.6 on 2025-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0032_clientcompany_closing_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                help_text="月末締めの場合は31、20日締めの場合は20",
                null=True,
                verbose_name="締め日",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("custom", "その他"),
                ],
                help_text="元請会社選択時に自動入力されます。案件ごとに編集可能です。",
                max_length=20,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の支払日（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
    ]
