# Generated by Django 4.2.6 on 2025-11-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0012_alter_subcontract_billed_amount"),
        ("order_management", "0033_project_closing_day_project_payment_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialorder",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subcontract_management.contractor",
                verbose_name="資材業者",
            ),
        ),
    ]
