# Generated by Django 4.2.6 on 2025-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0034_alter_materialorder_contractor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("mention", "メンション"),
                    ("comment", "コメント"),
                    ("project_update", "案件更新"),
                    ("work_completion_overdue", "完工遅延"),
                ],
                max_length=30,
                verbose_name="通知タイプ",
            ),
        ),
    ]
