# Generated by Django 5.2.6 on 2025-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0035_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="アーカイブ日時"),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="アーカイブ済み"),
        ),
    ]
