# Generated by Django 5.2.6 on 2025-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0036_notification_archived_at_notification_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="related_step",
            field=models.CharField(
                blank=True,
                help_text="このファイルが関連するステップ（例：estimate, survey）",
                max_length=50,
                null=True,
                verbose_name="関連ステップ",
            ),
        ),
    ]
