# Generated by Django 5.2.6 on 2025-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0037_add_related_step_to_projectfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="工事種別名"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("display_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "工事種別",
                "verbose_name_plural": "工事種別一覧",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
