# Generated by Django 5.2.6 on 2025-11-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0038_add_work_type_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="invoice_submission_deadline",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の請求書提出期限日（例：25日提出の場合は25）",
                null=True,
                verbose_name="請求書提出期限（日）",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="invoice_submission_notes",
            field=models.TextField(
                blank=True, help_text="例：毎月25日必着、月末必着など", verbose_name="請求書提出期限 補足説明"
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="pricing_tier",
            field=models.TextField(
                blank=True, help_text="例：A単価表、B単価のみ共有、1式◯万円など", verbose_name="単価帯・共有単価表"
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="response_ease_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "非常に低い"), (2, "低い"), (3, "普通"), (4, "高い"), (5, "とても高い")],
                help_text="連絡対応や意思決定のスムーズさを5段階で評価",
                null=True,
                verbose_name="対応のしやすさ",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="site_rules",
            field=models.TextField(
                blank=True, help_text="現場での注意事項やルールを箇条書きで入力", verbose_name="現場ルール"
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="trouble_tendencies",
            field=models.TextField(
                blank=True,
                help_text="例：追加書類が多い、現場変更が急、指示内容が曖昧など",
                verbose_name="トラブル傾向",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="work_ease_notes",
            field=models.TextField(
                blank=True, help_text="作業のしやすさに関する具体的な情報", verbose_name="作業のしやすさ 補足"
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="work_ease_rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "とても作業しにくい"),
                    (2, "作業しにくい"),
                    (3, "普通"),
                    (4, "作業しやすい"),
                    (5, "とても作業しやすい"),
                ],
                help_text="現場での作業のしやすさを5段階で評価",
                null=True,
                verbose_name="作業のしやすさ",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="work_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="この元請から依頼される工事の種類を選択",
                related_name="client_companies",
                to="order_management.worktype",
                verbose_name="対応可能な工事種別",
            ),
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="担当者名")),
                (
                    "personality_notes",
                    models.TextField(
                        blank=True,
                        help_text="担当者の性格や特徴、コミュニケーション時の注意点など",
                        verbose_name="性格・特徴",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="主担当者の場合はチェック", verbose_name="主担当"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="役職"),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "client_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="order_management.clientcompany",
                        verbose_name="元請会社",
                    ),
                ),
            ],
            options={
                "verbose_name": "担当者",
                "verbose_name_plural": "担当者一覧",
                "ordering": ["-is_primary", "display_order", "name"],
            },
        ),
    ]
