# Generated by Django 5.2.6 on 2025-11-25 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0039_clientcompany_invoice_submission_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sales_score_5",
                    models.DecimalField(
                        decimal_places=0,
                        default=10000000,
                        help_text="この金額以上で5点",
                        max_digits=12,
                        verbose_name="累計売上5点基準",
                    ),
                ),
                (
                    "total_sales_score_4",
                    models.DecimalField(
                        decimal_places=0,
                        default=5000000,
                        help_text="この金額以上で4点",
                        max_digits=12,
                        verbose_name="累計売上4点基準",
                    ),
                ),
                (
                    "total_sales_score_3",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        help_text="この金額以上で3点",
                        max_digits=12,
                        verbose_name="累計売上3点基準",
                    ),
                ),
                (
                    "total_sales_score_2",
                    models.DecimalField(
                        decimal_places=0,
                        default=500000,
                        help_text="この金額以上で2点",
                        max_digits=12,
                        verbose_name="累計売上2点基準",
                    ),
                ),
                (
                    "avg_sales_score_5",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        help_text="この金額以上で5点",
                        max_digits=12,
                        verbose_name="平均売上5点基準",
                    ),
                ),
                (
                    "avg_sales_score_4",
                    models.DecimalField(
                        decimal_places=0,
                        default=500000,
                        help_text="この金額以上で4点",
                        max_digits=12,
                        verbose_name="平均売上4点基準",
                    ),
                ),
                (
                    "avg_sales_score_3",
                    models.DecimalField(
                        decimal_places=0,
                        default=300000,
                        help_text="この金額以上で3点",
                        max_digits=12,
                        verbose_name="平均売上3点基準",
                    ),
                ),
                (
                    "avg_sales_score_2",
                    models.DecimalField(
                        decimal_places=0,
                        default=100000,
                        help_text="この金額以上で2点",
                        max_digits=12,
                        verbose_name="平均売上2点基準",
                    ),
                ),
                (
                    "profit_margin_score_5",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        help_text="この%以上で5点",
                        max_digits=5,
                        verbose_name="平均粗利益率5点基準",
                    ),
                ),
                (
                    "profit_margin_score_4",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="この%以上で4点",
                        max_digits=5,
                        verbose_name="平均粗利益率4点基準",
                    ),
                ),
                (
                    "profit_margin_score_3",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="この%以上で3点",
                        max_digits=5,
                        verbose_name="平均粗利益率3点基準",
                    ),
                ),
                (
                    "profit_margin_score_2",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="この%以上で2点",
                        max_digits=5,
                        verbose_name="平均粗利益率2点基準",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "verbose_name": "評価基準",
                "verbose_name_plural": "評価基準",
                "db_table": "rating_criteria",
            },
        ),
    ]
