# Generated by Django 5.2.6 on 2025-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0040_ratingcriteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="response_ease_notes",
            field=models.TextField(
                blank=True, help_text="対応のしやすさに関する具体的な情報", verbose_name="対応のしやすさ 補足"
            ),
        ),
    ]
