# Generated by Django 5.2.6 on 2025-11-25 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0041_add_response_ease_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcompany",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="clientcompany",
            name="email",
        ),
        migrations.RemoveField(
            model_name="clientcompany",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="clientcompany",
            name="website",
        ),
    ]
