# Generated by Django 5.2.6 on 2025-11-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0043_clientcompany_payment_offset_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="construction_status",
            field=models.CharField(
                choices=[
                    ("waiting", "着工日待ち"),
                    ("in_progress", "工事中"),
                    ("completed", "完工"),
                    ("cancelled", "キャンセル"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="工事ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="estimate_status",
            field=models.CharField(
                choices=[
                    ("not_issued", "未発行"),
                    ("issued", "見積もり書発行"),
                    ("under_review", "見積もり審査中"),
                    ("approved", "承認"),
                    ("cancelled", "キャンセル"),
                ],
                default="not_issued",
                max_length=20,
                verbose_name="見積もりステータス",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="survey_status",
            field=models.CharField(
                choices=[
                    ("not_required", "不要"),
                    ("required", "必要"),
                    ("scheduled", "予定済み"),
                    ("in_progress", "調査中"),
                    ("completed", "完了"),
                    ("cancelled", "キャンセル"),
                ],
                default="not_required",
                max_length=20,
                verbose_name="現地調査ステータス",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="witness_status",
            field=models.CharField(
                choices=[
                    ("waiting", "立ち会い待ち"),
                    ("in_progress", "立ち会い中"),
                    ("completed", "完了"),
                    ("cancelled", "キャンセル"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="立ち会いステータス",
            ),
        ),
    ]
