# Generated by Django 5.2.6 on 2025-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0044_alter_project_construction_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="payment_offset_months",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "当月"), (1, "翌月"), (2, "翌々月"), (3, "3ヶ月後")],
                help_text="締日から何ヶ月後に支払うか（0=当月、1=翌月、2=翌々月）",
                null=True,
                verbose_name="支払月",
            ),
        ),
    ]
