# Generated by Django 5.2.6 on 2025-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0045_project_payment_offset_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contractor_estimate_amount",
            field=models.TextField(
                blank=True, help_text="下請業者の見積金額（フリーテキスト）", verbose_name="下請業者見積金額"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="estimate_notes",
            field=models.TextField(
                blank=True, help_text="見積もりに関する備考・メモ", verbose_name="見積もり備考"
            ),
        ),
    ]
