# Generated by Django 5.2.6 on 2025-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0046_project_contractor_estimate_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="managed_units",
            field=models.IntegerField(
                blank=True, help_text="元請会社が管理している戸数", null=True, verbose_name="管理戸数"
            ),
        ),
    ]
