# Generated by Django 5.2.6 on 2025-11-28 07:33

from django.db import migrations


def set_default_payment_offset_months(apps, schema_editor):
    """
    全ての元請会社にデフォルトの支払月オフセット（翌月払い）を設定する
    """
    ClientCompany = apps.get_model('order_management', 'ClientCompany')

    # payment_offset_monthsがNullの会社に翌月払い（1）を設定
    updated_count = ClientCompany.objects.filter(
        payment_offset_months__isnull=True
    ).update(payment_offset_months='1')

    print(f"Updated {updated_count} client companies with default payment offset (翌月払い)")


def reverse_payment_offset_months(apps, schema_editor):
    """
    マイグレーションをロールバックする際の処理（Nullに戻す）
    """
    ClientCompany = apps.get_model('order_management', 'ClientCompany')

    # ロールバック時は元に戻さない（データは保持）
    # 必要に応じてNullに戻すこともできる
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0047_clientcompany_managed_units"),
    ]

    operations = [
        migrations.RunPython(
            set_default_payment_offset_months,
            reverse_payment_offset_months
        ),
    ]
