# Generated by Django 5.2.6 on 2025-11-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0048_set_default_payment_offset_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="order_management.comment",
                verbose_name="返信先コメント",
            ),
        ),
    ]
