# Generated by Django 5.2.6 on 2025-11-29 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0049_comment_parent_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"verbose_name": "ユーザープロファイル", "verbose_name_plural": "ユーザープロファイル"},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="プロフィール画像"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_background_color",
            field=models.CharField(
                choices=[
                    ("#007bff", "ブルー"),
                    ("#6c757d", "グレー"),
                    ("#28a745", "グリーン"),
                    ("#dc3545", "レッド"),
                    ("#ffc107", "イエロー"),
                    ("#17a2b8", "シアン"),
                    ("#6f42c1", "パープル"),
                    ("#fd7e14", "オレンジ"),
                    ("#e83e8c", "ピンク"),
                    ("#20c997", "ティール"),
                ],
                default="#007bff",
                max_length=7,
                verbose_name="アバター背景色",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profile",
        ),
    ]
