# Generated by Django 5.2.6 on 2025-11-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0050_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="incoming_payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "入金待ち"),
                    ("received", "入金済み"),
                    ("partial", "一部入金"),
                    ("overdue", "遅延"),
                ],
                default="pending",
                help_text="元請からの入金状況",
                max_length=20,
                verbose_name="入金ステータス",
            ),
        ),
    ]
