# Generated by Django 4.2.6 on 2025-11-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0051_project_incoming_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="会社名"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(blank=True, default="", verbose_name="住所"),
                ),
                (
                    "company_phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="電話番号"
                    ),
                ),
                (
                    "company_fax",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="FAX"
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "company_representative",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="代表者名"
                    ),
                ),
                (
                    "purchase_order_remarks",
                    models.TextField(
                        blank=True,
                        default="上記の通り発注いたします。\nご査収の程よろしくお願い申し上げます。",
                        help_text="発注書の備考欄に表示されるテキスト",
                        verbose_name="発注書 備考欄",
                    ),
                ),
                (
                    "invoice_remarks",
                    models.TextField(
                        blank=True,
                        default="上記の通り請求させていただきます。\nお支払いの程よろしくお願い申し上げます。",
                        help_text="請求書の備考欄に表示されるテキスト",
                        verbose_name="請求書 備考欄",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "会社設定",
                "verbose_name_plural": "会社設定",
                "db_table": "company_settings",
            },
        ),
    ]
