# Generated by Django 4.2.6 on 2025-11-30 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order_management", "0052_companysettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "ユーザープロファイル",
                "verbose_name_plural": "ユーザープロファイル一覧",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 30, 14, 35, 56, 38968, tzinfo=datetime.timezone.utc
                ),
                verbose_name="作成日時",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.JSONField(default=list, verbose_name="ロール"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
