# Generated by Django 4.2.6 on 2025-11-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0053_alter_userprofile_options_userprofile_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="invoice_custom_data",
            field=models.JSONField(
                blank=True,
                help_text="請求書のカスタマイズされたデータ（備考、工期、現場名など）",
                null=True,
                verbose_name="請求書カスタムデータ",
            ),
        ),
    ]
