# Generated by Django 4.2.6 on 2025-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0054_project_invoice_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/%Y/%m/",
                verbose_name="請求書PDFファイル",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="invoice_issued",
            field=models.BooleanField(default=False, verbose_name="請求書発行済み"),
        ),
    ]
