# Generated by Django 4.2.6 on 2025-11-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0055_project_invoice_file_alter_project_invoice_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="is_linked_file",
            field=models.BooleanField(
                default=False,
                help_text="他の案件のPDF（発注書・請求書）へのリンク",
                verbose_name="リンクファイル",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="linked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="ファイルがリンクされた日時（秒単位）",
                null=True,
                verbose_name="リンク作成日時",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="linked_source_file",
            field=models.CharField(
                blank=True,
                help_text="発注書または請求書のファイルパス",
                max_length=500,
                null=True,
                verbose_name="リンク元ファイルパス",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="linked_source_type",
            field=models.CharField(
                blank=True,
                choices=[("purchase_order", "発注書"), ("invoice", "請求書")],
                max_length=20,
                null=True,
                verbose_name="リンク元タイプ",
            ),
        ),
    ]
