# Generated by Django 4.2.6 on 2025-11-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_management",
            "0056_projectfile_is_linked_file_projectfile_linked_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="project_files/%Y/%m/",
                verbose_name="ファイル",
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file_size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ファイルサイズ（バイト）"
            ),
        ),
    ]
