# Generated by Django 4.2.6 on 2025-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0057_alter_projectfile_file_alter_projectfile_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_draft",
            field=models.BooleanField(
                default=False, help_text="下書き保存されたプロジェクト", verbose_name="下書き"
            ),
        ),
    ]
