# Generated by Django 5.2.6 on 2025-12-06 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0058_project_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="estimate_issued_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="survey_assignees",
        ),
        migrations.RemoveField(
            model_name="project",
            name="survey_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="survey_status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="witness_assignee_type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="witness_assignees",
        ),
        migrations.RemoveField(
            model_name="project",
            name="witness_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="witness_status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="work_end_completed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="work_end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="work_start_completed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="work_start_date",
        ),
    ]
