# Generated by Django 5.2.6 on 2025-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0059_remove_project_estimate_issued_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="material_labor_type",
            field=models.CharField(
                blank=True,
                choices=[("material_labor", "材工"), ("labor_only", "手間"), ("", "-")],
                default="",
                help_text="材工=資材発注含む、手間=材料支給のみ",
                max_length=20,
                verbose_name="材工/手間区分",
            ),
        ),
    ]
