# Generated by Django 4.2.6 on 2025-12-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0061_commentreadstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gross_profit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="売上 - 売上原価（自動計算・キャッシュ）",
                max_digits=12,
                verbose_name="粗利額",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="profit_margin",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="粗利額 / 売上 × 100（自動計算・キャッシュ）",
                max_digits=5,
                verbose_name="粗利率（%）",
            ),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="支払月の何日に支払うか（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="支払月の何日に支払うか（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="支払月の何日に支払うか（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
    ]
