# Generated by Django 4.2.6 on 2025-12-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0062_add_profit_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gross_profit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="売上 - 売上原価（自動計算・キャッシュ）",
                max_digits=12,
                verbose_name="粗利額",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="粗利額 / 売上 × 100（自動計算・キャッシュ）",
                max_digits=5,
                verbose_name="粗利率（%）",
            ),
        ),
    ]
