# Generated by Django 4.2.6 on 2025-12-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0064_add_payment_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                default=31,
                help_text="月末締めの場合は31、20日締めの場合は20。デフォルト: 31（月末）",
                null=True,
                verbose_name="締め日",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("custom", "その他"),
                ],
                default="monthly",
                help_text="元請会社選択時に自動入力されます。案件ごとに編集可能です。デフォルト: 月1回",
                max_length=20,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                default=31,
                help_text="支払月の何日に支払うか（1-31）。例：25日払いの場合は25。デフォルト: 31（月末）",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="payment_offset_months",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "当月"), (1, "翌月"), (2, "翌々月"), (3, "3ヶ月後")],
                default=1,
                help_text="締日から何ヶ月後に支払うか（0=当月、1=翌月、2=翌々月）。デフォルト: 1（翌月）",
                null=True,
                verbose_name="支払月",
            ),
        ),
    ]
