# Generated by Django 4.2.6 on 2026-02-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0024_unify_payment_cycle_choices"),
        ("order_management", "0065_add_project_payment_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_start_date",
                    models.DateField(help_text="この業者の作業開始日", verbose_name="作業開始日"),
                ),
                (
                    "work_end_date",
                    models.DateField(help_text="この業者の作業終了日", verbose_name="作業終了日"),
                ),
                (
                    "work_description",
                    models.CharField(
                        blank=True,
                        help_text="例: 電気工事、配管工事、内装工事など",
                        max_length=200,
                        verbose_name="作業内容",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="作業の順序（数字が小さいほど先に表示）", verbose_name="表示順序"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="その他のメモや注意事項", verbose_name="備考"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        help_text="作業を行う業者",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subcontract_management.contractor",
                        verbose_name="業者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_schedules",
                        to="order_management.project",
                        verbose_name="案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "業者スケジュール",
                "verbose_name_plural": "業者スケジュール",
                "ordering": ["project", "order", "work_start_date"],
            },
        ),
    ]
