# Generated by Django 5.2.6 on 2025-09-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工事業者名")),
                ("address", models.TextField(verbose_name="工事業者住所")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, verbose_name="担当者名"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "contractor_type",
                    models.CharField(
                        choices=[("individual", "個人職人"), ("company", "協力会社")],
                        default="company",
                        max_length=20,
                        verbose_name="業者種別",
                    ),
                ),
                ("specialties", models.TextField(blank=True, verbose_name="得意分野")),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="時給単価",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "外注先",
                "verbose_name_plural": "外注先一覧",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectProfitAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="総売上"
                    ),
                ),
                (
                    "total_subcontract_cost",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="外注費合計"
                    ),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="部材費合計"
                    ),
                ),
                (
                    "total_expense",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="総支出"
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=12, verbose_name="粗利益"
                    ),
                ),
                (
                    "profit_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="利益率(%)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.project",
                        verbose_name="対象案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件別利益分析",
                "verbose_name_plural": "案件別利益分析一覧",
            },
        ),
        migrations.CreateModel(
            name="Subcontract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("management_no", models.CharField(max_length=20, verbose_name="管理No")),
                ("site_name", models.CharField(max_length=200, verbose_name="現場名")),
                ("site_address", models.TextField(verbose_name="現場住所")),
                (
                    "contract_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="依頼金額"
                    ),
                ),
                (
                    "billed_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="被請求額"
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateField(blank=True, null=True, verbose_name="出金予定日"),
                ),
                (
                    "payment_date",
                    models.DateField(blank=True, null=True, verbose_name="出金日"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "未払い"),
                            ("processing", "処理中"),
                            ("paid", "支払済"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="出金状況",
                    ),
                ),
                (
                    "material_item_1",
                    models.CharField(blank=True, max_length=100, verbose_name="部材費項目①"),
                ),
                (
                    "material_cost_1",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="部材費代①"
                    ),
                ),
                (
                    "material_item_2",
                    models.CharField(blank=True, max_length=100, verbose_name="部材費項目②"),
                ),
                (
                    "material_cost_2",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="部材費代②"
                    ),
                ),
                (
                    "material_item_3",
                    models.CharField(blank=True, max_length=100, verbose_name="部材費項目③"),
                ),
                (
                    "material_cost_3",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="部材費代③"
                    ),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="部材費合計"
                    ),
                ),
                (
                    "purchase_order_issued",
                    models.BooleanField(default=False, verbose_name="発注書発行"),
                ),
                ("work_description", models.TextField(blank=True, verbose_name="作業内容")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subcontract_management.contractor",
                        verbose_name="工事業者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_management.project",
                        verbose_name="関連案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "外注管理",
                "verbose_name_plural": "外注管理一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
