# Generated by Django 5.2.6 on 2025-09-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcontract",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "作業管理",
                "verbose_name_plural": "作業管理一覧",
            },
        ),
        migrations.AddField(
            model_name="subcontract",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=6,
                null=True,
                verbose_name="見積工数（時間）",
            ),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="internal_department",
            field=models.CharField(blank=True, max_length=50, verbose_name="所属部署"),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="internal_hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=8,
                null=True,
                verbose_name="時給単価",
            ),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="internal_worker_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="担当者名"),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="worker_type",
            field=models.CharField(
                choices=[("external", "外注"), ("internal", "社内リソース")],
                default="external",
                max_length=20,
                verbose_name="作業者タイプ",
            ),
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subcontract_management.contractor",
                verbose_name="工事業者",
            ),
        ),
    ]
