# Generated by Django 5.2.6 on 2025-09-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0002_alter_subcontract_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                (
                    "employee_id",
                    models.CharField(max_length=20, unique=True, verbose_name="社員番号"),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("construction", "施工部"),
                            ("sales", "営業部"),
                            ("design", "設計部"),
                            ("management", "管理部"),
                            ("quality", "品質管理"),
                            ("safety", "安全管理"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="所属部署",
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=50, verbose_name="役職"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="電話番号"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="標準時給"
                    ),
                ),
                ("specialties", models.TextField(blank=True, verbose_name="専門分野")),
                ("skills", models.TextField(blank=True, verbose_name="スキル・資格")),
                ("is_active", models.BooleanField(default=True, verbose_name="在職中")),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="入社日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "社内担当者",
                "verbose_name_plural": "社内担当者一覧",
                "ordering": ["department", "name"],
            },
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="internal_worker_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="担当者名（手動入力）"
            ),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="internal_worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subcontract_management.internalworker",
                verbose_name="社内担当者",
            ),
        ),
    ]
