# Generated by Django 5.2.6 on 2025-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0003_internalworker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="dynamic_material_costs",
            field=models.JSONField(blank=True, default=list, verbose_name="動的部材費情報"),
        ),
    ]
