# Generated by Django 5.2.6 on 2025-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0004_subcontract_dynamic_material_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="internal_pricing_type",
            field=models.CharField(
                choices=[("hourly", "時給ベース"), ("project", "案件単位")],
                default="hourly",
                max_length=20,
                verbose_name="料金体系",
            ),
        ),
    ]
