# Generated by Django 5.2.6 on 2025-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0005_subcontract_internal_pricing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="dynamic_cost_items",
            field=models.JSONField(blank=True, default=list, verbose_name="動的費用項目"),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="tax_type",
            field=models.CharField(
                choices=[("include", "税込"), ("exclude", "税抜")],
                default="include",
                max_length=10,
                verbose_name="税込/税抜",
            ),
        ),
    ]
