# Generated by Django 5.2.6 on 2025-09-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0006_subcontract_dynamic_cost_items_subcontract_tax_type",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractor",
            options={
                "ordering": ["name"],
                "verbose_name": "発注先",
                "verbose_name_plural": "発注先一覧",
            },
        ),
        migrations.AlterModelOptions(
            name="subcontract",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "発注管理",
                "verbose_name_plural": "発注管理一覧",
            },
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subcontract_management.contractor",
                verbose_name="発注先",
            ),
        ),
    ]
