# Generated by Django 5.2.6 on 2025-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0007_alter_contractor_options_alter_subcontract_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="account_holder",
            field=models.CharField(blank=True, max_length=100, verbose_name="口座名義"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="口座番号"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("ordinary", "普通"), ("current", "当座"), ("savings", "貯蓄")],
                default="ordinary",
                max_length=10,
                verbose_name="口座種別",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="銀行名"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="branch_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="支店名"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月払い"),
                    ("bimonthly", "隔月払い"),
                    ("quarterly", "四半期払い"),
                    ("custom", "その他"),
                ],
                default="monthly",
                max_length=10,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の支払日（1-31）。例：25日払いの場合は25",
                null=True,
                verbose_name="支払日",
            ),
        ),
    ]
