# Generated by Django 4.2.6 on 2025-10-31 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0008_contractor_account_holder_contractor_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="ContractorReviewからの平均評価（1-5）",
                max_digits=3,
                verbose_name="平均評価",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="certifications",
            field=models.TextField(
                blank=True, help_text="改行区切りで複数入力可能", verbose_name="保有資格"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="last_project_date",
            field=models.DateField(blank=True, null=True, verbose_name="最終案件日"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="service_areas",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='例: ["東京23区", "神奈川県全域"]',
                verbose_name="対応可能地域",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="skill_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='例: ["電気工事", "空調工事", "給排水工事"]',
                verbose_name="スキルカテゴリ",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="skill_level",
            field=models.CharField(
                choices=[
                    ("beginner", "初級"),
                    ("intermediate", "中級"),
                    ("advanced", "上級"),
                    ("expert", "エキスパート"),
                ],
                default="intermediate",
                max_length=20,
                verbose_name="スキルレベル",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="success_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=100.0,
                help_text="問題なく完了した案件の割合",
                max_digits=5,
                verbose_name="成功率(%)",
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="total_projects",
            field=models.IntegerField(default=0, verbose_name="総案件数"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="trust_level",
            field=models.IntegerField(
                default=3,
                help_text="1-5の5段階評価。4以上はCLが直接アサイン可能",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="信頼度",
            ),
        ),
    ]
