# Generated by Django 4.2.6 on 2025-11-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0009_contractor_average_rating_contractor_certifications_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontract",
            name="management_no",
            field=models.CharField(blank=True, max_length=20, verbose_name="管理No"),
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="site_address",
            field=models.TextField(blank=True, verbose_name="現場住所"),
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="site_name",
            field=models.CharField(blank=True, max_length=200, verbose_name="現場名"),
        ),
    ]
