# Generated by Django 4.2.6 on 2025-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0010_alter_subcontract_management_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontract",
            name="billed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="被請求額",
            ),
        ),
    ]
