# Generated by Django 4.2.6 on 2025-11-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0012_alter_subcontract_billed_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("attendance", "立ち会い"),
                    ("survey", "現調"),
                    ("construction_start", "着工"),
                ],
                max_length=20,
                null=True,
                verbose_name="対象ステップ",
            ),
        ),
    ]
