# Generated by Django 4.2.6 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0013_subcontract_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月払い"),
                    ("bimonthly", "隔月払い"),
                    ("quarterly", "四半期払い"),
                    ("custom", "その他"),
                ],
                help_text="未設定の場合は発注先のデフォルト値を使用",
                max_length=10,
                null=True,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AddField(
            model_name="subcontract",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の支払日（1-31）。未設定の場合は発注先のデフォルト値を使用",
                null=True,
                verbose_name="支払日",
            ),
        ),
    ]
