# Generated by Django 4.2.6 on 2025-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0014_subcontract_payment_cycle_subcontract_payment_day",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                help_text="毎月の締日（1-31）。例：月末締めの場合は31、20日締めの場合は20",
                null=True,
                verbose_name="締日",
            ),
        ),
    ]
