# Generated by Django 4.2.6 on 2025-11-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0015_contractor_closing_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="payment_offset_months",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "当月"), (1, "翌月"), (2, "翌々月"), (3, "3ヶ月後")],
                help_text="締日から何ヶ月後に支払うか（0=当月、1=翌月、2=翌々月）",
                null=True,
                verbose_name="支払月",
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="contractor_type",
            field=models.CharField(
                choices=[
                    ("individual", "個人職人"),
                    ("company", "協力会社"),
                    ("material", "資材"),
                ],
                default="company",
                max_length=20,
                verbose_name="業者種別",
            ),
        ),
    ]
