# Generated by Django 5.2.6 on 2025-11-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0016_contractor_payment_offset_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontract",
            name="contract_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="発注金額",
            ),
        ),
    ]
