# Generated by Django 5.2.6 on 2025-11-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0017_alter_subcontract_contract_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="purchase_order_file",
            field=models.FileField(
                blank=True,
                help_text="発注書のPDFや画像ファイル",
                null=True,
                upload_to="purchase_orders/%Y/%m/",
                verbose_name="発注書ファイル",
            ),
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="purchase_order_issued",
            field=models.BooleanField(default=False, verbose_name="発注書発行済み"),
        ),
    ]
