# Generated by Django 4.2.6 on 2025-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0018_subcontract_purchase_order_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="invoice_file",
            field=models.FileField(
                blank=True,
                help_text="請求書のPDFや画像ファイル",
                null=True,
                upload_to="invoices/%Y/%m/",
                verbose_name="請求書ファイル",
            ),
        ),
    ]
