# Generated by Django 4.2.6 on 2025-11-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0019_subcontract_invoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontract",
            name="purchase_order_custom_data",
            field=models.JSONField(
                blank=True,
                help_text="発注書のカスタマイズされたデータ（備考、工期、現場名など）",
                null=True,
                verbose_name="発注書カスタムデータ",
            ),
        ),
    ]
