# Generated by Django 5.2.6 on 2025-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0020_subcontract_purchase_order_custom_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontract",
            name="step",
            field=models.CharField(
                blank=True,
                choices=[
                    ("step_attendance", "立ち会い"),
                    ("step_survey", "現調"),
                    ("step_estimate", "見積書発行"),
                    ("step_construction_start", "着工"),
                    ("step_completion", "完工"),
                    ("step_contract", "契約"),
                    ("step_invoice", "請求書発行"),
                    ("step_permit_application", "許可申請"),
                    ("step_material_order", "資材発注"),
                    ("step_inspection", "検査"),
                ],
                max_length=50,
                null=True,
                verbose_name="対象ステップ",
            ),
        ),
    ]
