# Generated by Django 5.2.6 on 2025-12-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0021_alter_subcontract_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorFieldCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="スラッグ"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "業者フィールドカテゴリ",
                "verbose_name_plural": "業者フィールドカテゴリ一覧",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="contractor",
            name="custom_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='動的に定義されたフィールドの値を格納。形式: {"field_slug": "value", ...}',
                verbose_name="カスタムフィールド",
            ),
        ),
        migrations.CreateModel(
            name="ContractorFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="フィールド名")),
                ("slug", models.SlugField(max_length=100, verbose_name="スラッグ")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "テキスト"),
                            ("number", "数値"),
                            ("date", "日付"),
                            ("select", "選択肢"),
                            ("multiselect", "複数選択"),
                            ("checkbox", "チェックボックス"),
                            ("textarea", "テキストエリア"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="フィールドタイプ",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ヘルプテキスト"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="プレースホルダー"
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='例: ["選択肢1", "選択肢2", "選択肢3"]',
                        verbose_name="選択肢",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="必須")),
                (
                    "min_value",
                    models.IntegerField(blank=True, null=True, verbose_name="最小値"),
                ),
                (
                    "max_value",
                    models.IntegerField(blank=True, null=True, verbose_name="最大値"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="subcontract_management.contractorfieldcategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "業者フィールド定義",
                "verbose_name_plural": "業者フィールド定義一覧",
                "ordering": ["category__order", "order", "name"],
                "unique_together": {("category", "slug")},
            },
        ),
    ]
