# Generated by Django 4.2.6 on 2025-12-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subcontract_management",
            "0022_contractorfieldcategory_contractor_custom_fields_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="closing_day",
            field=models.IntegerField(
                blank=True,
                default=31,
                help_text="毎月の締日（1-31）。例：月末締めの場合は31、20日締めの場合は20。デフォルト: 31（月末）",
                null=True,
                verbose_name="締日",
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="payment_day",
            field=models.IntegerField(
                blank=True,
                default=31,
                help_text="毎月の支払日（1-31）。例：25日払いの場合は25。デフォルト: 31（月末）",
                null=True,
                verbose_name="支払日",
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="payment_offset_months",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "当月"), (1, "翌月"), (2, "翌々月"), (3, "3ヶ月後")],
                default=1,
                help_text="締日から何ヶ月後に支払うか（0=当月、1=翌月、2=翌々月）。デフォルト: 1（翌月）",
                null=True,
                verbose_name="支払月",
            ),
        ),
    ]
