# Generated by Django 4.2.6 on 2025-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontract_management", "0023_add_payment_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("custom", "その他"),
                ],
                default="monthly",
                max_length=10,
                verbose_name="支払サイクル",
            ),
        ),
        migrations.AlterField(
            model_name="subcontract",
            name="payment_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "月1回"),
                    ("bimonthly", "月2回"),
                    ("weekly", "週1回"),
                    ("custom", "その他"),
                ],
                help_text="未設定の場合は発注先のデフォルト値を使用",
                max_length=10,
                null=True,
                verbose_name="支払サイクル",
            ),
        ),
    ]
